#define WINDOW_HEIGTH 1040
#define WINDOW_WIDTH 1920

#define INITIAL_SPAWN_COORDINATE_Y WINDOW_HEIGTH/2
#define INITIAL_SPAWN_COORDINATE_X WINDOW_WIDTH/2
#define WIDTH_PG_IMAGE 100
#define HEIGTH_PG_IMAGE 100

#define DIAGONAL_FACTOR 0.66

#define NUMBER_OF_TEXTS 18
#define NUM_KEYS 1024

#define MOVING_SPEED 5

#define MAIN_MAP_HEIGTH 1040
#define MAIN_MAP_WIDTH 1920
#define MAIN_MAP_X_POSITION 0
#define MAIN_MAP_Y_POSITION 0



#define SECOND_IN_MICRO 1000000
#define FPS 70

#define MAX_TRAPS_NUMBER 4





